const COMPETITORS_API_ERROR_DEFAULT = 'oops! something went wrong.';
const NO_DATA_RESULT_MESSAGE = 'There is no data.';
const COMPETITORS_API_RATE = 1000;
const SCORE_INCREMENTAL_MIN_AMOUNT = 100;
const SCORE_INCREMENTAL_MAX_AMOUNT = 500;
const COMPETITOR_CARD_HEIGHT = 60;
const COMPETITOR_CARD_WIDTH = 400;

export {
  COMPETITORS_API_ERROR_DEFAULT,
  NO_DATA_RESULT_MESSAGE,
  COMPETITORS_API_RATE,
  SCORE_INCREMENTAL_MIN_AMOUNT,
  SCORE_INCREMENTAL_MAX_AMOUNT,
  COMPETITOR_CARD_HEIGHT,
  COMPETITOR_CARD_WIDTH,
};
